"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Project = { id: string; name: string };
export default function TestimonialForm() {
  const supabase = createClient(); const [projects,setProjects]=useState<Project[]>([]); const [submitted,setSubmitted]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  useEffect(() => { supabase.from("projects").select("id,name").eq("is_active",true).order("display_order").then(({data})=>setProjects(data ?? [])); }, []);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setSaving(true); setError(""); const form=new FormData(e.currentTarget); const rating=Number(form.get("rating"));
    const {error: insertError}=await supabase.from("testimonials").insert({client_name:String(form.get("client_name")??"").trim(),company:String(form.get("company")??"").trim(),role:String(form.get("role")??"").trim()||null,content:String(form.get("content")??"").trim(),rating,photo_url:String(form.get("photo_url")??"").trim()||null,project_id:String(form.get("project_id")??"").trim()||null,status:"pending",featured:false});
    if(insertError){setError("We couldn’t submit your testimonial. Please try again.");setSaving(false);return;} setSubmitted(true);setSaving(false);
  }
  if(submitted) return <div className="rounded-card border border-[var(--color-border)] bg-[var(--color-surface)] p-8 text-center"><p className="text-sm font-semibold tracking-[0.14em] text-[var(--color-accent-blue)]">THANK YOU</p><h2 className="text-h2 mt-2">Your testimonial has been submitted.</h2><p className="text-body mx-auto mt-4 max-w-xl text-[var(--color-text-secondary)]">We appreciate you taking the time to share your experience. Your testimonial will be reviewed before anything is published on the Kaytech website.</p></div>;
  return <form onSubmit={submit} className="rounded-card border border-[var(--color-border)] bg-[var(--color-surface)] p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2">
    <label className="text-sm font-medium">Your name<input required name="client_name" maxLength={120} className="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] px-4 py-3 outline-none focus:border-[var(--color-accent-blue)]" /></label>
    <label className="text-sm font-medium">Business / company<input required name="company" maxLength={160} className="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] px-4 py-3 outline-none focus:border-[var(--color-accent-blue)]" /></label>
    <label className="text-sm font-medium">Your role<input name="role" maxLength={120} placeholder="Founder, CEO, Manager..." className="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] px-4 py-3 outline-none focus:border-[var(--color-accent-blue)]" /></label>
    <label className="text-sm font-medium">Rating<select required name="rating" defaultValue="5" className="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] px-4 py-3 outline-none focus:border-[var(--color-accent-blue)]">{[5,4,3,2,1].map(v=><option key={v} value={v}>{"★".repeat(v)} ({v}/5)</option>)}</select></label>
    <label className="text-sm font-medium sm:col-span-2">What did Kaytech work on for you?<select name="project_id" defaultValue="" className="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] px-4 py-3 outline-none focus:border-[var(--color-accent-blue)]"><option value="">Select a project (optional)</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <label className="text-sm font-medium sm:col-span-2">Your experience<textarea required name="content" minLength={20} maxLength={1200} rows={6} placeholder="Tell us about your experience working with Kaytech..." className="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] px-4 py-3 outline-none focus:border-[var(--color-accent-blue)]" /></label>
    <label className="text-sm font-medium sm:col-span-2">Photo URL <span className="font-normal text-[var(--color-text-secondary)]">(optional)</span><input name="photo_url" type="url" maxLength={500} placeholder="https://..." className="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] px-4 py-3 outline-none focus:border-[var(--color-accent-blue)]" /></label>
  </div><label className="mt-5 flex items-start gap-3 text-sm text-[var(--color-text-secondary)]"><input required type="checkbox" className="mt-1" /><span>I give Kaytech permission to publish this testimonial on its website.</span></label>
  {error ? <p className="mt-4 text-sm text-red-500">{error}</p> : null}<button disabled={saving} className="mt-6 rounded-xl bg-[var(--color-accent-blue)] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Submitting…" : "Submit testimonial"}</button></form>;
}